/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.am.view.leave.type;

import com.smsc.am.controller.LeaveTypeController;
import com.smsc.am.model.LeaveType;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SASANGA
 */
public class LeaveTypeView extends javax.swing.JFrame {

    private final LeaveTypeController typeController;
    private ArrayList<LeaveType> listLeaveTypes;
    private int selectedRow;
    private LeaveType selectedLeaveType;
    private String typeName;

    /**
     * Creates new form LeaveType
     */
    public LeaveTypeView() {
        this.selectedRow = -1;
        initComponents();
        typeController = new LeaveTypeController();
        setLocationRelativeTo(null);
        loadAllLeaveTypes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXImagePanel1 = new org.jdesktop.swingx.JXImagePanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeaveName = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTypeDescription = new javax.swing.JTextArea();
        btnDeleteLeaveType = new javax.swing.JButton();
        btnEditLeaveType = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        manageMenu = new javax.swing.JMenu();
        newTypeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Leve Types");
        setResizable(false);

        jXImagePanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setToolTipText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblLeaveName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLeaveName.setGridColor(new java.awt.Color(255, 255, 255));
        tblLeaveName.setRowHeight(25);
        tblLeaveName.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblLeaveName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeaveNameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLeaveName);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        txtTypeDescription.setEditable(false);
        txtTypeDescription.setColumns(20);
        txtTypeDescription.setRows(5);
        jScrollPane2.setViewportView(txtTypeDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        btnDeleteLeaveType.setText("Delete");
        btnDeleteLeaveType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLeaveTypeActionPerformed(evt);
            }
        });

        btnEditLeaveType.setText("Edit");
        btnEditLeaveType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLeaveTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXImagePanel1Layout = new javax.swing.GroupLayout(jXImagePanel1);
        jXImagePanel1.setLayout(jXImagePanel1Layout);
        jXImagePanel1Layout.setHorizontalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXImagePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditLeaveType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteLeaveType)))
                .addContainerGap())
        );
        jXImagePanel1Layout.setVerticalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteLeaveType)
                    .addComponent(btnEditLeaveType))
                .addContainerGap())
        );

        manageMenu.setText("Manage");

        newTypeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newTypeMenuItem.setText("New");
        newTypeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTypeMenuItemActionPerformed(evt);
            }
        });
        manageMenu.add(newTypeMenuItem);

        jMenuBar1.add(manageMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTypeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTypeMenuItemActionPerformed
        NewLeaveType newLeaveType = new NewLeaveType();
        newLeaveType.setLeaveTypeView(this);
        newLeaveType.setVisible(true);
    }//GEN-LAST:event_newTypeMenuItemActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tblLeaveNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeaveNameMouseClicked
        selectedRow = tblLeaveName.getSelectedRow();
        loadDescription();
    }//GEN-LAST:event_tblLeaveNameMouseClicked

    private void btnDeleteLeaveTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLeaveTypeActionPerformed
        if (selectedRow > -1) {
            deleteLeaveTypes();
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row !!!!!");
        }
    }//GEN-LAST:event_btnDeleteLeaveTypeActionPerformed

    private void btnEditLeaveTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLeaveTypeActionPerformed
        if (selectedRow > -1) {
            showUpdatePopup();
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row !!!!!");
        }
    }//GEN-LAST:event_btnEditLeaveTypeActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveTypeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveTypeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveTypeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveTypeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveTypeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteLeaveType;
    private javax.swing.JButton btnEditLeaveType;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXImagePanel jXImagePanel1;
    private javax.swing.JMenu manageMenu;
    private javax.swing.JMenuItem newTypeMenuItem;
    private javax.swing.JTable tblLeaveName;
    private javax.swing.JTextArea txtTypeDescription;
    // End of variables declaration//GEN-END:variables

    private void loadAllLeaveTypes() {
        try {
            listLeaveTypes = typeController.listLeaveTypes();
            DefaultTableModel dtm = (DefaultTableModel) tblLeaveName.getModel();
            dtm.setRowCount(0);
            this.selectedRow = -1;
            this.selectedLeaveType = null;
            txtTypeDescription.setText("");
            for (LeaveType leaveType : listLeaveTypes) {
                Object[] row = {leaveType.getName()};
                dtm.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LeaveTypeView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Server error orcked in list leavetypes", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void loadLeaveTypeFromOutSide() {
        loadAllLeaveTypes();
    }
    
    private void loadDescription() {
        String deName = tblLeaveName.getValueAt(selectedRow, 0).toString();
        for (LeaveType leaveType : listLeaveTypes) {
            if (leaveType.getName().equals(deName)) {
                txtTypeDescription.setText(leaveType.getDescription());
                selectedLeaveType = leaveType;
            }
        }
    }

    private void deleteLeaveTypes() {
        int confirm = JOptionPane.showConfirmDialog(this, "Are you want to delete this leave type ?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean isDeleteLeaveTypeById = typeController.deleteLeaveTypeById(selectedLeaveType.getId());
                if (isDeleteLeaveTypeById) {
                    JOptionPane.showMessageDialog(this, "Leave type delete success!", "success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Leave type delete unsuccessfull!", "warning", JOptionPane.WARNING_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(LeaveTypeView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void showUpdatePopup() {
        UpdateLeaveType updateLeaveType = new UpdateLeaveType(this, true);
        updateLeaveType.setLeaveType(selectedLeaveType);
        updateLeaveType.setLeaveTypeView(this);
        updateLeaveType.setVisible(true);
    }
}
