/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smsc.am.view.login;

import com.smsc.am.controller.LogInController;
import com.smsc.am.view.home.HomePage;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SASANGA
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.error.setVisible(false);
        setLocationRelativeTo(null);
        setSize(480, 285);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        passowrdTxt = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        loginMainLabel = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 260));
        setMinimumSize(new java.awt.Dimension(480, 260));
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(480, 260));
        loginPanel.setPreferredSize(new java.awt.Dimension(480, 260));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("User Name : ");
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password : ");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, -1));

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        loginPanel.add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 186, 28));
        loginPanel.add(passowrdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 186, 28));

        loginbtn.setBackground(new java.awt.Color(0, 51, 51));
        loginbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(0, 51, 51));
        loginbtn.setText("Log In");
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        loginMainLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loginMainLabel.setForeground(new java.awt.Color(51, 51, 51));
        loginMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginMainLabel.setText("Log In");
        loginPanel.add(loginMainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 51));

        error.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPanel.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Attendnce Mark V1.0.0.001 copyright @ smsc");
        loginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 480, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsc/am/view/images/login_back.png"))); // NOI18N
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        loginToSystem();
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel loginMainLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passowrdTxt;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables

    private void loginToSystem() {
        String name = userNameTxt.getText();
        String pass = passowrdTxt.getText();
        if (!name.equals("") && !pass.equals("")) {
            LogInController logInController = new LogInController();
            try {
                boolean isLogin = logInController.login(name, pass);
                if (isLogin) {
                    new HomePage().setVisible(true);
                    this.setVisible(false);
                } else {
                    this.error.setText("Enterd user name or password not match to our recodes");
                    this.error.setVisible(true);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                this.error.setText("Log in error. Please try again!");
                this.error.setVisible(true);
            }
        } else {
            this.error.setText("Please type user name and password");
            this.error.setVisible(true);
        }
    }
}
